version: '3.8'

services:
  web:
    image: chelmerd/nginx:v1
    build:
      context: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/nginx.conf.template
    ports:
      - 443:443
    environment:
      - DOMAIN_NAME
      - CERTS_
      - CERT_KEY
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"