version: '3.8'
services:
  nginx:
    image: chelmerd/nginx:v1
    build:
      context: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/nginx.conf.template
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network
    ports:
      - 443:443
    environment:
      - DOMAIN_NAME
      - CERTS_
      - CERT_KEY
    # only replace certain env vars
    command: /bin/sh -c "envsubst '$$DOMAIN_NAME $$CERTS_ $$CERT_KEY' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    restart: unless-stopped

  db:
    image: chelmerd/mariadb:v1
    build:
      context: ./requirements/mariadb/
    volumes:
      - ./requirements/mariadb/tools/my.cnf:/etc/my.cnf
      - ./requirements/mariadb/tools/init.sql:/usr/local/bin/init.sql
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WORDPRESS_DB_NAME
      - TZ
    networks:
      - inception_network
    # restart: unless-stopped
    # command: /bin/sh -c "chown -R mysql:mysql /var/lib/mysql && /usr/bin/mysqld --user=mysql --init-file=/usr/local/bin/init.sql"

  wordpress:
    image: chelmerd/wordpress-fpm:v1
    build:
      context: ./requirements/wordpress
    depends_on:
      - db
    networks:
      - inception_network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_WEBSITE_TITLE: ${WORDPRESS_WEBSITE_TITLE}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_ADMIN: ${WORDPRESS_ADMIN}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./requirements/wordpress/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - wp_data:/var/www/html
      - ./requirements/wordpress/setup.sh:/usr/local/bin/setup.sh
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chelmerd/data/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chelmerd/data/wp

networks:
  inception_network:
    driver: bridge
